config/routes.rb
Rails.application.routes.draw do

  get 'weixins/show'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'callbacks'
                                  }
  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts
  end

  root 'groups#index'

  namespace :account do
    resources :groups
    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :title, presence: { message: "此栏必填！	 "}

	has_many :posts, dependent: :destroy
	has_many :group_users
	has_many :members, through: :group_users, source: :user

	belongs_to :owner, class_name: "User", foreign_key: :user_id

	def editable_by?(user)
		user && user == owner
	end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :group, counter_cache: :posts_count
	belongs_to :author, class_name: "User", foreign_key: :user_id

	validates :content, presence: true

	scope :recent, -> { order("updated_at DESC")}

	def editable_by?(user)
		user && user == author
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  def is_member_of?(group)
  	participated_groups.include?(group)
  end

  def join!(group)
  	participated_groups << group
  end

  def quit!(group)
  	participated_groups.delete(group)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
	before_action :authenticate_user!

	def index
		@groups = current_user.participated_groups.order("posts_count DESC")
	end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
	before_action :authenticate_user!

	def index
		@posts = current_user.posts.recent
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  	end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
	def github
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

	def index
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])
		@posts = @group.posts.page(params[:page]).per(8)
		@post = @group.posts.new
	end

	def new
		@group = Group.new
	end

	def edit
		@group = current_user.groups.find(params[:id])
	end

	def create
		@group = current_user.groups.build(group_params)

		if @group.save
			current_user.join!(@group)
			redirect_to groups_path, notice: "新增讨论版成功"
		else
			render :new
		end
	end

	def update
		@group = current_user.groups.find(params[:id])

		if @group.update(group_params)
			redirect_to groups_path, notice: "讨论版修改成功!"
		else
			render :edit
		end
	end

	def destroy
		@group = current_user.groups.find(params[:id])

		@group.destroy
		redirect_to groups_path, alert: "讨论版删除成功!"
	end

	def join
		@group = Group.find(params[:id])

		if !current_user.is_member_of?(@group)
			current_user.join!(@group)
			flash[:notice] = "加入本讨论版成功！"
		else
			flash[:warning] = "你已经是本讨论版成员了！"
		end

		redirect_to group_path(@group)
	end

	def quit
		@group = Group.find(params[:id])

		if current_user.is_member_of?(@group)
			current_user.quit!(@group)
			flash[:alert] = "已退出本讨论版！"
		else
			flash[:warning] = "你不是本讨论版成员，怎么退出 XD"
		end

		redirect_to group_path(@group)
	end

	private
		def group_params
			params.require(:group).permit(:title, :description)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!
	before_action :find_group
	before_action :member_required, only: [:new, :create]

	def new
		@post = @group.posts.new
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def create
		@post = @group.posts.build(post_params)
		@post.author = current_user

		respond_to do |format|
			if @post.save
				# redirect_to group_path(@group), notice: "新增文章成功！"
				format.html {}
				format.js
			else
				format.html { render :new }
				format.js
			end
		end
	end

	def update
		@post = current_user.posts.find(params[:id])

		if @post.update(post_params)
			redirect_to group_path(@group), notice: "文章修改成功！"
		else
			render :edit
		end
	end

	def destroy
		@post = current_user.posts.find(params[:id])

		@post.destroy
		redirect_to group_path(@group), alert: "文章已删除！"
	end

	private

		def post_params
			params.require(:post).permit(:content)
		end

		def find_group
			@group = Group.find(params[:group_id])
		end

		def member_required
			return if current_user.is_member_of?(@group)
			flash[:warning] = "你不是这个讨论版的成员，不能发文喔！"
			redirect_to group_path(@group)
		end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	layout 'layouts/users_form'
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	layout 'layouts/users_form'
end

app/controllers/weixins_controller.rb
class WeixinsController < ApplicationController
	skip_before_filter :verify_authenticity_token

	 def show
	 	@signature = params["signature"]
	 	@timestamp = params["timestamp"]
	 	@nonce = params["nonce"]
	 	    
 	  	@token = "weixin"
 	  	@tmpArr = [@token, @timestamp, @nonce]
 	  	@tmpArr.sort!
 	  	@tmpStr = @tmpArr.join
 	  	@tmpStr = Digest::SHA1.hexdigest( @tmpStr )
	 		
 	  	if @tmpStr == @signature
 	  		render text: params["echostr"]
 	  	else
 	  		render nothing: true
 	    	end
	 end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def notice_msg
		alert_types = { notice: :success, alert: :danger }

		close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
		close_button = content_tag(:button, "x", close_button_options)

		alerts = flash.map do |name,msg|
			alert_content = close_button + msg
			alert_type = alert_types[name.to_sym] || name
			alert_class = "alert alert-#{alert_type} alert-dismissable"
			content_tag(:div, alert_content, class: alert_class)
		end

		alerts.join("\n").html_safe
	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def render_post_content(post)
		truncate(simple_format(post.content), length: 100)
	end
end

app/views/common/_footer.html.erb
<footer class="container-fluid" style="margin-top: 100px;">
	<p class="text-center">
		Copyright ©2015 高老庄 Design by <a href="http://github.com/Gaolz/" target="_new">Gaolz</a>
	</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="navbar-header"><%= link_to image_tag("header.png", id: 'glz-headpicture'), root_path %></div>
	<div class="collapse navbar-collapse">
		<ul class="nav nav-pills navbar-right">
			<% if !current_user %>
				<li><%= link_to("注册", new_user_registration_path) %></li>
				<li><%= link_to("登入", new_user_session_path) %></li>
			<% else %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<%= current_user.name %>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to("加入的组", account_groups_path) %></li>
						<li><%= link_to("文章", account_posts_path) %></li>
						<li><%= link_to("设置", edit_user_registration_path) %></li>
					</ul>
				</li>
				<li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
	<div class="from-group">
		<%= f.input :title, input_html: {class: "form-control"} %>
		<%= f.input :description, input_html: {class: "form-control"} %>
	</div>
	<%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1>修改讨论版</h1>
	<hr>
	<%= render "form" %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
	<table class="table table-hover">
		<thead>
			<tr>
				<td>组名</td>
				<td>概述</td>
			</tr>
		</thead>
		<tbody>
			<% @groups.each do |group| %>
				<tr>
					<td><%= link_to(truncate(group.title, length: 15), group_path(group)) %></td>
					<td><%= group.description %></td>
					<td>
						<% if current_user && group.editable_by?(current_user) %>
							<%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default") %>
							<%= link_to("Delete", group_path(group), method: :delete, data: { confirm: "Are you sure? "}, class: "btn btn-sm btn-default") %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<div class="group">
		<%= link_to("创建讨论组", new_group_path, class: "btn btn-primary pull-right") %>
	</div>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1>新增讨论版</h1>
	<hr>
	<%= render "form" %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
	<div class="group">
		<% if @group.editable_by?(current_user) %>
			<%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right") %>
		<% end %>
		<% if current_user.present? %>
			<% if current_user.is_member_of?(@group) %>
				<%= link_to("Quit", quit_group_path(@group), method: :post, class: "btn btn-danger") %>
			<% else %>
				<%= link_to("Join", join_group_path(@group), method: :post, class: "btn btn-info") %>
			<% end %>
		<% end %>
	</div>
	<h2><%= @group.title %></h2>
	<p><%= @group.description %></p>

	<table class="table">
		<thead>
			<tr>
				<th>文章</th>
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<td><%= render_post_content(post) %></td>
					<td>
						<% if current_user && post.editable_by?(current_user) %>
							<%= link_to("Edit", edit_group_post_path(post.group, post), class: "btn btn-default btn-xs") %>
							<%= link_to("Delete", group_post_path(post.group, post), class: "btn btn-default btn-xs", method: :delete, data: { confirm: "Are you sure?" }) %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<div>
		<%= simple_form_for([@group, @post], remote: true) do |f| %>
			<div class="form-group">
				<%= f.input :content, as: :text, input_html: { class: "form-control" }, label: false %>
			</div>
			<div class="form-action">
				<%= f.submit "发表评论", disable_with: "Submiting...", class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
	<%= paginate @posts %>
</div>

app/views/layouts/_post_form.html.erb
<tr>
	<td><%= render_post_content(post) %></td>
	<td>
		<% if current_user && post.editable_by?(current_user) %>
			<%= link_to("Edit", edit_group_post_path(post.group, post), class: "btn btn-default btn-xs") %>
			<%= link_to("Delete", group_post_path(post.group, post), class: "btn btn-default btn-xs", method: :delete, data: { confirm: "Are you sure?" }) %>
		<% end %>
	</td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101s</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<%= render "common/navbar" %>
	<%= notice_msg %>
	<%= yield %>
</div>
	<%= render "common/footer" %>

</body>
</html>

app/views/layouts/users_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>高老庄</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="users-form-header">
  <%= link_to "/users/auth/github", class: "pull-right" do %>
  	<i class="fa fa-github fa-3x"></i>
  <% end %>
	<%= link_to "主页", root_path, class: "btn btn-info pull-left" %>
	<% if params[:controller] == 'users/registrations' %>
		<%= link_to "登录", new_user_session_path, class: "btn btn-success pull-right" %>
	<% else %>
		<%= link_to "注册", new_user_registration_path, class: "btn btn-success pull-right" %>
	<% end %>
</div>
<img src=<%= "#{asset_path("night.jpg")}" %> alt="背景图" id="rainyday">
<div class="container-fluid">
	<%= notice_msg %>
	<div class="wallpaper">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/posts/create.js.erb
$("tbody>tr:last-child").after("<%= escape_javascript(render(partial: 'layouts/post_form', locals: {post: @post})) %>")
$("#post_content").val("")

app/views/posts/edit.html.erb
<h1 class="text-center">修改文章</h1>
<div class="col-md-4 col-md-offset-4">
	<%= simple_form_for [@group, @post] do |f| %>
		<div class="form-group">
			<%= f.input :content, input_html: { class: "form-control" } %>
		</div>
		<div class="form-action">
			<%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>